import { defineConfig } from "tinacms";

/**
 * TinaCMS for a plain static site.
 *
 * The site is generated by the Python scripts in the repo root, not by a JS
 * framework, so Tina's job here is narrow and deliberate: it edits the JSON
 * files in /content, commits them to GitHub, and the Cloudflare Pages build
 * re-runs the generators. Tina never touches the HTML directly.
 *
 * That boundary is the point. Shayla can change the words, the cohort dates
 * and the FAQ without any chance of breaking layout, schema or accessibility.
 *
 * Env vars (set in Cloudflare Pages → Settings → Environment variables):
 *   NEXT_PUBLIC_TINA_CLIENT_ID   from app.tina.io → your project → Overview
 *   TINA_TOKEN                   from the same screen (read-only token)
 *   TINA_SEARCH_TOKEN            optional, only if you enable search
 */

const branch =
  process.env.GITHUB_BRANCH ||
  process.env.CF_PAGES_BRANCH ||
  process.env.HEAD ||
  "main";

export default defineConfig({
  branch,
  clientId: process.env.NEXT_PUBLIC_TINA_CLIENT_ID!,
  token: process.env.TINA_TOKEN!,

  // `tinacms build` writes the editor here; the site is served from the repo
  // root, so /admin/index.html ends up alongside the generated pages.
  build: {
    outputFolder: "admin",
    publicFolder: ".",
  },
  media: {
    tina: {
      mediaRoot: "assets/img",
      publicFolder: ".",
    },
  },

  schema: {
    collections: [
      // ─────────────────────────────────────────────── Homepage
      {
        name: "home",
        label: "Homepage",
        path: "content",
        format: "json",
        match: { include: "home" },
        ui: {
          allowedActions: { create: false, delete: false },
        },
        fields: [
          {
            type: "object",
            name: "hero",
            label: "Hero (top of the page)",
            fields: [
              { type: "string", name: "eyebrow", label: "Small line above the headline" },
              {
                type: "string",
                name: "headline",
                label: "Headline",
                ui: { component: "textarea" },
                description:
                  "Wrap words in *asterisks* to set them in the gold italic. Use <br> to force a line break.",
              },
              { type: "string", name: "intro", label: "Intro paragraph", ui: { component: "textarea" } },
              { type: "string", name: "button1", label: "Primary button" },
              { type: "string", name: "button2", label: "Secondary button" },
            ],
          },
          {
            type: "object",
            name: "trust",
            label: "Three points under the hero",
            fields: [
              { type: "string", name: "item1", label: "Point 1" },
              { type: "string", name: "item2", label: "Point 2" },
              { type: "string", name: "item3", label: "Point 3" },
            ],
          },
          {
            type: "object",
            name: "about",
            label: "Welcome section",
            fields: [
              { type: "string", name: "headline", label: "Headline" },
              { type: "string", name: "intro", label: "Intro paragraph", ui: { component: "textarea" } },
            ],
          },
          {
            type: "object",
            name: "services",
            label: "Services section",
            fields: [{ type: "string", name: "headline", label: "Headline" }],
          },
          {
            type: "object",
            name: "team",
            label: "Team section",
            fields: [{ type: "string", name: "headline", label: "Headline" }],
          },
          {
            type: "object",
            name: "insurance",
            label: "Insurance section",
            fields: [{ type: "string", name: "headline", label: "Headline" }],
          },
          {
            type: "object",
            name: "cta",
            label: "Closing call to action",
            fields: [{ type: "string", name: "headline", label: "Headline" }],
          },
        ],
      },

      // ─────────────────────────────────────────────── Group cohort
      // The highest-churn content on the site — this changes every cohort.
      {
        name: "group",
        label: "Mama's Golden Hour — cohort",
        path: "content",
        format: "json",
        match: { include: "group" },
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "name", label: "Group name" },
          {
            type: "datetime",
            name: "startDateISO",
            label: "Start date and time",
            description:
              "Used by Google for the event listing. Set the other two date fields to match.",
          },
          {
            type: "string",
            name: "startDateLong",
            label: "Start date, written out",
            description: 'Shown in the details table. e.g. "Wednesday 7 October 2026"',
          },
          {
            type: "string",
            name: "startDateShort",
            label: "Start date, short",
            description: 'Used in card blurbs and page descriptions. e.g. "7 October"',
          },
          { type: "string", name: "time", label: "Time" },
          { type: "string", name: "runsFor", label: "Runs for" },
          { type: "string", name: "where", label: "Where" },
          { type: "string", name: "sessionLength", label: "Session length" },
          { type: "string", name: "pricePerSession", label: "Price per session (number only)" },
          { type: "string", name: "priceFull", label: "Price for the full run (number only)" },
          {
            type: "string",
            name: "costLine",
            label: "Cost, written out",
            description: 'Shown in the table. e.g. "$25 per session, or $150 for the full six weeks"',
          },
          { type: "string", name: "openTo", label: "Open to" },
          { type: "string", name: "capacity", label: "Maximum group size" },
          {
            type: "boolean",
            name: "enrolling",
            label: "Currently enrolling",
            description: "Untick when the cohort fills. The page then says the group is closed.",
          },
        ],
      },

      // ─────────────────────────────────────────────── Practice details
      {
        name: "practice",
        label: "Practice details",
        path: "content",
        format: "json",
        match: { include: "practice" },
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "legalName", label: "Legal name" },
          { type: "string", name: "phone", label: "Phone, as displayed" },
          {
            type: "string",
            name: "phoneHref",
            label: "Phone, as dialled",
            description: 'Must stay in the form tel:+13037369822',
          },
          { type: "string", name: "email", label: "Email" },
          {
            type: "boolean",
            name: "acceptingNewClients",
            label: "Accepting new clients",
          },
          { type: "string", name: "insurers", label: "Insurance plans", list: true },
          { type: "string", name: "instagram", label: "Instagram URL" },
          { type: "string", name: "psychologyToday", label: "Psychology Today URL" },
          { type: "string", name: "footerBlurb", label: "Footer blurb", ui: { component: "textarea" } },
        ],
      },

      // ─────────────────────────────────────────────── FAQ
      {
        name: "faq",
        label: "FAQ",
        path: "content",
        format: "json",
        match: { include: "faq" },
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          {
            type: "object",
            name: "items",
            label: "Questions",
            list: true,
            ui: {
              itemProps: (item) => ({ label: item?.question || "New question" }),
            },
            fields: [
              { type: "string", name: "question", label: "Question" },
              {
                type: "string",
                name: "answer",
                label: "Answer",
                ui: { component: "textarea" },
                description:
                  "Plain sentences. Separate paragraphs with a blank line. Basic HTML links are allowed.",
              },
            ],
          },
        ],
      },
    ],
  },
});
